const neighborhoods = [
    { name: 'alameda', value: '46' },
    { name: 'albany / el cerrito', value: '47' },
    { name: 'berkeley', value: '48' },
    { name: 'berkeley north / hills', value: '49' },
    { name: 'concord / pleasant hill / martinez', value: '51' },
    { name: 'danville / san ramon', value: '52' },
    { name: 'dublin / pleasanton / livermore', value: '53' },
    { name: 'fremont / union city / newark', value: '54' },
    { name: 'hayward / castro valley', value: '55' },
    { name: 'hercules, pinole, san pablo, el sob', value: '56' },
    { name: 'lafayette / orinda / moraga', value: '57' },
    { name: 'oakland downtown', value: '58' },
    { name: 'oakland east', value: '59' },
    { name: 'oakland hills / mills', value: '60' },
    { name: 'oakland lake merritt / grand', value: '61' },
    { name: 'oakland north / temescal', value: '62' },
    { name: 'oakland piedmont / montclair', value: '63' },
    { name: 'oakland west', value: '64' },
    { name: 'richmond / point / annex', value: '65' },
    { name: 'oakland rockridge / claremont', value: '66' },
    { name: 'san leandro', value: '67' },
    { name: 'vallejo / benicia', value: '68' },
    { name: 'walnut creek', value: '69' },
    { name: 'emeryville', value: '112' },
    { name: 'pittsburg / antioch', value: '113' },
    { name: 'brentwood / oakley', value: '142' },
    { name: 'fairfield / vacaville', value: '154' },
  ];

  export default neighborhoods;