amenities_list = ["Air Conditioning",
                                                "Heating System",
                                                "Laundry Facilities",
                                                "Dishwasher",
                                                "Refrigerator",
                                                "Stove/Oven",
                                                "Microwave",
                                                "Garbage Disposal",
                                                "Internet Access",
                                                "Cable-Ready Outlets",
                                                "Balcony/Patio",
                                                "Storage Space",
                                                "Covered Parking",
                                                "Garage",
                                                "Pool",
                                                "Fitness Center",
                                                "Clubhouse",
                                                "Playground",
                                                "Pet-Friendly Options",
                                                "Security System",
                                                "On-site Management",
                                                "Elevator",
                                                "Public Transportation Access",
                                                "Smoke-Free Environment",
                                                "Wheelchair Access"] 